import { Undo2 } from "lucide-react";
import "./studio.css";
import Link from "next/link";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}{" "}
        <Link href={"/"} className="go_back ">
          <Undo2 width={15} height={15} /> <span> Go Back</span>
        </Link>
      </body>
    </html>
  );
}
